export const notesData = [
    {
        index: 0,
        active: false,
        column: 0,
        audio: '0',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 1,
        active: false,
        column: 1,
        audio: '0',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 2,
        active: false,
        column: 2,
        audio: '0',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 3,
        active: false,
        column: 3,
        audio: '0',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 4,
        active: false,
        column: 4,
        audio: '0',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 5,
        active: false,
        column: 5,
        audio: '0',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 6,
        active: false,
        column: 6,
        audio: '0',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 7,
        active: false,
        column: 7,
        audio: '0',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 8,
        active: false,
        column: 0,
        audio: '1',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 9,
        active: false,
        column: 1,
        audio: '1',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 10,
        active: false,
        column: 2,
        audio: '1',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 11,
        active: false,
        column: 3,
        audio: '1',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 12,
        active: false,
        column: 4,
        audio: '1',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 13,
        active: false,
        column: 5,
        audio: '1',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 14,
        active: false,
        column: 6,
        audio: '1',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 15,
        active: false,
        column: 7,
        audio: '1',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 16,
        active: false,
        column: 0,
        audio: '2',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 17,
        active: false,
        column: 1,
        audio: '2',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 18,
        active: false,
        column: 2,
        audio: '2',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 19,
        active: false,
        column: 3,
        audio: '2',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 19,
        active: false,
        column: 4,
        audio: '2',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 21,
        active: false,
        column: 5,
        audio: '2',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 22,
        active: false,
        column: 6,
        audio: '2',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 23,
        active: false,
        column: 7,
        audio: '2',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 24,
        active: false,
        column: 0,
        audio: '3',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 25,
        active: false,
        column: 1,
        audio: '3',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 26,
        active: false,
        column: 2,
        audio: '3',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 27,
        active: false,
        column: 3,
        audio: '3',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 28,
        active: false,
        column: 4,
        audio: '3',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 29,
        active: false,
        column: 5,
        audio: '3',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 30,
        active: false,
        column: 6,
        audio: '3',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 31,
        active: false,
        column: 7,
        audio: '3',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 32,
        active: false,
        column: 0,
        audio: '4',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 33,
        active: false,
        column: 1,
        audio: '4',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 34,
        active: false,
        column: 2,
        audio: '4',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 35,
        active: false,
        column: 3,
        audio: '4',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 36,
        active: false,
        column: 4,
        audio: '4',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 37,
        active: false,
        column: 5,
        audio: '4',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 38,
        active: false,
        column: 6,
        audio: '4',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 39,
        active: false,
        column: 7,
        audio: '4',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 49,
        active: false,
        column: 0,
        audio: '5',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 41,
        active: false,
        column: 1,
        audio: '5',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 42,
        active: false,
        column: 2,
        audio: '5',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 43,
        active: false,
        column: 3,
        audio: '5',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 44,
        active: false,
        column: 4,
        audio: '5',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 45,
        active: false,
        column: 5,
        audio: '5',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 46,
        active: false,
        column: 6,
        audio: '5',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 47,
        active: false,
        column: 7,
        audio: '5',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 48,
        active: false,
        column: 0,
        audio: '6',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 49,
        active: false,
        column: 1,
        audio: '6',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 50,
        active: false,
        column: 2,
        audio: '6',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 51,
        active: false,
        column: 3,
        audio: '6',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 52,
        active: false,
        column: 4,
        audio: '6',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 53,
        active: false,
        column: 5,
        audio: '6',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 54,
        active: false,
        column: 6,
        audio: '6',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 55,
        active: false,
        column: 7,
        audio: '6',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 56,
        active: false,
        column: 0,
        audio: '7',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 57,
        active: false,
        column: 1,
        audio: '7',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 58,
        active: false,
        column: 2,
        audio: '7',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 59,
        active: false,
        column: 3,
        audio: '7',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 69,
        active: false,
        column: 4,
        audio: '7',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 61,
        active: false,
        column: 5,
        audio: '7',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 62,
        active: false,
        column: 6,
        audio: '7',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 63,
        active: false,
        column: 7,
        audio: '7',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 64,
        active: false,
        column: 0,
        audio: '8',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 65,
        active: false,
        column: 1,
        audio: '8',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 66,
        active: false,
        column: 2,
        audio: '8',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 67,
        active: false,
        column: 3,
        audio: '8',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 68,
        active: false,
        column: 4,
        audio: '8',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 69,
        active: false,
        column: 5,
        audio: '8',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 70,
        active: false,
        column: 6,
        audio: '8',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 71,
        active: false,
        column: 7,
        audio: '8',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 72,
        active: false,
        column: 0,
        audio: '9',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 73,
        active: false,
        column: 1,
        audio: '9',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 74,
        active: false,
        column: 2,
        audio: '9',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 75,
        active: false,
        column: 3,
        audio: '9',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 76,
        active: false,
        column: 4,
        audio: '9',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 77,
        active: false,
        column: 5,
        audio: '9',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 78,
        active: false,
        column: 6,
        audio: '9',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 79,
        active: false,
        column: 7,
        audio: '9',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 89,
        active: false,
        column: 0,
        audio: '10',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 81,
        active: false,
        column: 1,
        audio: '10',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 82,
        active: false,
        column: 2,
        audio: '10',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 83,
        active: false,
        column: 3,
        audio: '10',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 84,
        active: false,
        column: 4,
        audio: '10',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 85,
        active: false,
        column: 5,
        audio: '10',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 86,
        active: false,
        column: 6,
        audio: '10',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 87,
        active: false,
        column: 7,
        audio: '11',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 88,
        active: false,
        column: 0,
        audio: '11',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 89,
        active: false,
        column: 1,
        audio: '11',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 90,
        active: false,
        column: 2,
        audio: '11',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 91,
        active: false,
        column: 3,
        audio: '11',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 92,
        active: false,
        column: 4,
        audio: '11',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 93,
        active: false,
        column: 5,
        audio: '11',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 94,
        active: false,
        column: 6,
        audio: '11',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 95,
        active: false,
        column: 7,
        audio: '12',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 96,
        active: false,
        column: 0,
        audio: '12',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 97,
        active: false,
        column: 1,
        audio: '12',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 98,
        active: false,
        column: 2,
        audio: '12',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 99,
        active: false,
        column: 3,
        audio: '12',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 100,
        active: false,
        column: 4,
        audio: '12',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 101,
        active: false,
        column: 5,
        audio: '12',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 102,
        active: false,
        column: 6,
        audio: '12',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 103,
        active: false,
        column: 7,
        audio: '13',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 104,
        active: false,
        column: 0,
        audio: '13',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 105,
        active: false,
        column: 1,
        audio: '13',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 106,
        active: false,
        column: 2,
        audio: '13',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 107,
        active: false,
        column: 3,
        audio: '13',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 108,
        active: false,
        column: 4,
        audio: '13',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 109,
        active: false,
        column: 5,
        audio: '13',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 110,
        active: false,
        column: 6,
        audio: '13',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 111,
        active: false,
        column: 7,
        audio: '14',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 112,
        active: false,
        column: 0,
        audio: '14',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 113,
        active: false,
        column: 1,
        audio: '14',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 114,
        active: false,
        column: 2,
        audio: '14',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 115,
        active: false,
        column: 3,
        audio: '14',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 116,
        active: false,
        column: 4,
        audio: '14',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 117,
        active: false,
        column: 5,
        audio: '14',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 118,
        active: false,
        column: 6,
        audio: '14',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    },
    {
        index: 119,
        active: false,
        column: 7,
        audio: '14',
        endTime: 46753,
        pitchName: 'A',
        pitch: 67,
    }
]
